name: randomquotes
description: Random Quotes App.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.2.4
  http: ^1.1.0
  package_info_plus: ^4.2.0
  share_plus: ^7.2.2
  url_launcher: ^6.2.4
  velocity_x: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    #- assets/images/
    - assets/lang/
    - assets/icons/
